/* EPA 608 2026 training paper — original shop questions.
   Length and topics match the proctored exam: 25 Core / I / II / III, 18/25 (72%) each.
   NOT the copyrighted ESCO / HVAC Excellence / Prometric item bank.
   Official card is sat with an EPA-approved proctor. CFR wins. */
(function (global) {
  "use strict";

  function Q(section, q, choices, a, why) {
    return { section: section, pack: "epa608", q: q, choices: choices, a: a, why: why };
  }

  const CORE = [
    Q("core", "Before opening a sealed refrigeration system that still holds refrigerant you must:",
      ["Vent slowly to atmosphere", "Recover the refrigerant", "Add nitrogen until empty", "Run pump-down and walk away"], 1,
      "Section 608 requires recovery before opening. Venting is illegal except de minimis with certified gear."),
    Q("core", "Venting CFC and HCFC refrigerants became illegal on:",
      ["January 1, 1987", "July 1, 1992", "November 15, 1995", "January 1, 2010"], 1,
      "July 1, 1992 for CFC/HCFC. November 15, 1995 added HFC and most substitutes."),
    Q("core", "Venting HFC refrigerants (R-134a, R-410A class) became illegal on:",
      ["July 1, 1992", "November 15, 1993", "November 15, 1995", "January 1, 2020"], 2,
      "November 15, 1995. 1992 was CFC/HCFC. 1993 is the recovery-machine date."),
    Q("core", "R-22 belongs to which refrigerant family?",
      ["CFC", "HCFC", "HFC", "HFO"], 1,
      "R-22 is an HCFC (chlorine + hydrogen). R-12 is CFC. R-410A / 134a are HFC."),
    Q("core", "Which family has the highest ozone-depletion potential?",
      ["HFCs", "HFOs", "CFCs", "Hydrocarbons"], 2,
      "CFCs (R-11, R-12, R-502). Chlorine eats ozone. HFCs have zero ODP but high GWP."),
    Q("core", "The Montreal Protocol is:",
      ["A U.S. state licensing law", "The international treaty to phase out ozone-depleting substances", "A compressor oil spec", "OSHA lockout"], 1,
      "1987 treaty. Clean Air Act Section 608 is how the U.S. puts it on the truck."),
    Q("core", "Recovered refrigerant may be sold to a new owner only after it is:",
      ["Recycled on the truck", "Reclaimed to AHRI 700 purity", "Mixed 50/50 with virgin", "Sat 30 days in the bottle"], 1,
      "Reclaim is off-site to AHRI 700. Recycle stays with the same owner."),
    Q("core", "The three R's of 608 are:",
      ["Recover, recycle, reclaim", "Repair, recharge, replace", "Recover, reclaim, retrofit", "Reduce, reuse, recycle"], 0,
      "Recover = take it out. Recycle = clean on the truck. Reclaim = plant, AHRI 700."),
    Q("core", "Self-contained recovery equipment:",
      ["Uses the appliance compressor only", "Has its own compressor/pump to pull refrigerant", "Is illegal after 2010", "Works only on Type III"], 1,
      "Its own pump. System-dependent (passive) uses the appliance compressor — Type I only."),
    Q("core", "A refillable recovery cylinder is typically:",
      ["White with a green top", "Gray with a yellow top", "All yellow disposable", "Any empty paint can"], 1,
      "DOT refillable: gray body, yellow top. Weigh it. Never recover into a disposable."),
    Q("core", "Fill a recovery cylinder to no more than about:",
      ["100% liquid", "80% of capacity by weight", "Until the relief valve dumps", "Whatever fits in the van"], 1,
      "80% by weight leaves vapor headspace so a hot truck does not hydrostatically rupture it."),
    Q("core", "Disposable (DOT-39) refrigerant cylinders should be:",
      ["Reused as recovery tanks", "Used as designed, heel recovered, then scrapped — never used for recovery", "Heated with a torch to empty", "Filled from the recovery machine"], 1,
      "Never recover into disposables. Recover the heel, disable the valve, recycle the steel."),
    Q("core", "Mixing two different refrigerants in one recovery cylinder is:",
      ["Fine if pressures are close", "A way to stretch R-22", "Not allowed — creates a contaminated mixture", "Required for Type III"], 2,
      "Never mix. The bottle becomes hazardous waste nobody wants."),
    Q("core", "Leak-test with:",
      ["Pure oxygen", "Shop air from the compressor", "Dry nitrogen (never oxygen)", "More refrigerant until it hisses"], 2,
      "Dry nitrogen. Oxygen + oil is explosive. Shop air is wet and dirty."),
    Q("core", "Who may purchase CFC, HCFC, and most HFC refrigerants?",
      ["Anyone over 18", "Certified Section 608 technicians", "Homeowners with a receipt", "Only EPA employees"], 1,
      "Sales restriction: 608 card. Wholesaler can ask to see it."),
    Q("core", "Section 609 covers:",
      ["Stationary HVAC/R (this card)", "Motor vehicle air conditioning", "EPA civil penalties only", "Type III chillers"], 1,
      "609 is cars. 608 is stationary appliances. Different law, different card."),
    Q("core", "Universal 608 means you passed:",
      ["Core only", "Core plus Type I, II, and III", "OSHA 30 plus Core", "Type II twice"], 1,
      "Universal = all four sections. Core alone authorizes no equipment."),
    Q("core", "Passing score on a proctored 608 section is:",
      ["15 of 25 (60%)", "17 of 25 (68%)", "18 of 25 (72%)", "21 of 25 (84%) always"], 2,
      "18 of 25, 72%, each section scored alone. 84% is the Type I open-book mail-in bar."),
    Q("core", "A recovery cylinder should be hydrostatically retested about every:",
      ["1 year", "2 years", "5 years", "Never"], 2,
      "Typically 5 years for refillable DOT bottles. Date is stamped on the collar."),
    Q("core", "HFC refrigerants such as R-410A typically use which oil?",
      ["Mineral oil only", "POE (polyolester)", "Water", "Gasoline"], 1,
      "POE with HFCs. Mineral oil was CFC/HCFC. There is no drop-in oil swap."),
    Q("core", "Zeotropic blends (400-series) can:",
      ["Never leak", "Fractionate — leak and change composition", "Be topped off forever with no effect", "Only be used in cars"], 1,
      "They leak the high-pressure component first. Weigh in. Don't pressure-charge."),
    Q("core", "A2L refrigerants (R-32, R-454B) are:",
      ["Nonflammable like R-410A", "Mildly flammable, lower GWP replacements", "Explosives", "Type III only"], 1,
      "ASHRAE 2L: mildly flammable. 2026 new residential iron is mostly A2L. Follow UL 60335-2-40."),
    Q("core", "The EPA buckets refrigerants (high / medium / low pressure) by:",
      ["What the tech feels on the gauges", "Liquid saturation pressure at 104°F", "Boiling point at the North Pole", "Cylinder color only"], 1,
      "104°F liquid sat pressure. R-410A is high-pressure. R-134a is medium. R-123 is low."),
    Q("core", "De minimis release means:",
      ["You may vent a pound to save time", "A good-faith recovery with certified equipment may leave a tiny leftover", "Any leak under 50 lb is legal to ignore", "Type I always vents"], 1,
      "Good-faith certified recovery, not opening a system and walking. Not a free pound."),
    Q("core", "Core certification by itself lets you service:",
      ["Any split system", "Nothing — Core is required but authorizes no equipment alone", "Window units", "Cars"], 1,
      "Fail Core and you fail the cert. Pass Core alone and you still cannot open a box."),
  ];

  const TYPE1 = [
    Q("type1", "Type I covers appliances that are:",
      ["Any unit under 5 tons", "Factory-hermetic with a manufactured charge of 5 lb or less", "Any split with 5 lb remaining", "MVAC on cars"], 1,
      "Both must be true: factory sealed AND nameplate ≤ 5 lb. Remaining charge does not reclassify a split."),
    Q("type1", "Which is a Type I appliance?",
      ["3-ton 410A split", "Household refrigerator", "R-123 centrifugal chiller", "Walk-in cooler"], 1,
      "Fridge, freezer, window AC, PTAC, dehumidifier, vending, water cooler."),
    Q("type1", "A residential 410A split with 6 lb on the nameplate is:",
      ["Type I", "Type II", "Type III", "Section 609"], 1,
      "Splits are Type II even at 6 lb. Type I is factory-hermetic small appliances."),
    Q("type1", "A window unit nameplated 4 lb that a tech overcharged to 7 lb is still:",
      ["Type II because it now holds 7 lb", "Type I — manufactured charge rules", "Type III", "Universal only"], 1,
      "Manufactured (nameplate) charge, not what someone stuffed in later."),
    Q("type1", "On a small appliance with a running compressor, post-1993 recovery gear, recover at least:",
      ["50% of the charge", "80% of the charge", "90% of the charge or 4 inches Hg", "10 inches Hg always"], 2,
      "90% if the compressor runs, or 4\" Hg. 80% if the compressor is dead."),
    Q("type1", "Small appliance, compressor will not run, post-1993 machine. Recover at least:",
      ["50%", "80% of the charge or 4 inches Hg", "90% only", "0 psig is enough always"], 1,
      "Dead compressor: 80% or 4\" Hg. Running compressor is the 90% bar."),
    Q("type1", "System-dependent (passive) recovery is legal on:",
      ["Type I only", "Type II splits", "Type III chillers", "Any 608 appliance"], 0,
      "Passive uses the appliance compressor. Type I only. Don't empty a split that way."),
    Q("type1", "Self-contained recovery on Type I:",
      ["Is illegal", "Has its own compressor and may be used on small appliances", "Requires the system compressor", "Only works on R-12"], 1,
      "Self-contained works on Type I. Passive is the Type-I-only extra."),
    Q("type1", "A piercing valve on a small appliance should be:",
      ["Left on as a permanent port", "Used to recover, then removed — not a service port", "Installed with oxygen", "Required on every split"], 1,
      "Temporary access. Don't leave it to leak for the next ten years."),
    Q("type1", "When recovering from a small appliance you should:",
      ["Recover from the high side only always", "Install access on both high and low when possible so you get more of the charge", "Vent the vapor, recover only liquid", "Skip recovery if under 1 lb"], 1,
      "Both sides when you can. Under 5 lb is not a free vent."),
    Q("type1", "Non-condensables in a recovered Type I charge usually mean:",
      ["The gas is extra cold", "Air got in — the recovered cylinder pressure sits high for the temperature", "You must add more oil", "Type III rules apply"], 1,
      "Air. Compare cylinder P/T. Don't put dirty air back in a fridge."),
    Q("type1", "Household refrigerators typically use which oil with HFC-134a?",
      ["Mineral", "POE or the OEM specified oil", "Water", "PAG only (cars)"], 1,
      "OEM oil. PAG is mostly 609 MVAC. Don't mix."),
    Q("type1", "If a small appliance is leaking so badly you cannot hit 80/90% or 4\" Hg:",
      ["Vent the rest", "Recover what you can, document why you stopped", "Ignore 608", "Switch to Type III numbers"], 1,
      "Recover what you can and write it down. Not a license to blow the charge."),
    Q("type1", "Type I open-book mail-in passing score is:",
      ["72% (18/25)", "75%", "80%", "84% (21/25)"], 3,
      "Mail-in open book is 84%. Proctored Type I is still 18/25 (72%)."),
    Q("type1", "MVAC (car AC) is certified under:",
      ["Type I", "Type II", "Section 609, not 608 Type I", "Universal 608 only"], 2,
      "Cars are 609. A window unit is 608 Type I. Don't mix the cards."),
    Q("type1", "After Nov 15, 1993, recovery machines used on small appliances must be able to recover:",
      ["50% regardless of compressor", "80% (compressor off) or 90% (compressor on), or 4\" Hg", "10\" Hg on every fridge", "25 mm Hg absolute"], 1,
      "That's the Type I recovery standard. 10\" and 25 mm Hg are Type II / III."),
    Q("type1", "Which is NOT a Type I appliance?",
      ["PTAC", "Dehumidifier", "Packaged terminal heat pump under 5 lb factory charge", "Split-system air conditioner"], 3,
      "Any split is Type II. PTACs and windows that meet the 5 lb hermetic rule are Type I."),
    Q("type1", "When disposing of a household refrigerator you must:",
      ["Leave the charge for scrap", "Recover to Type I standards before the final disposal", "Vent because it's under 5 lb", "Cut the tube and drain oil only"], 1,
      "Final disposal still requires recovery. Scrap yards want it empty and tagged."),
    Q("type1", "A fitting that requires a piercing saddle because there is no process stub:",
      ["Means you may vent", "Is common on older Type I boxes — recover through a proper piercing tool", "Converts it to Type II", "Requires 15\" Hg"], 1,
      "No port ≠ vent. Pierce, recover, cap."),
    Q("type1", "Charge for Type I classification is determined from:",
      ["What a gauge says today", "The manufacturer's nameplate charge", "The recovery cylinder weight only", "SEER rating"], 1,
      "Nameplate manufactured charge. Not the leftover."),
    Q("type1", "Using the system compressor to recover (passive) on a Type II split is:",
      ["Required", "Not allowed — passive is Type I only", "Fine if you hit 0 psig", "The 15\" Hg method"], 1,
      "Don't ride a split compressor to empty it for 608. Use self-contained recovery."),
    Q("type1", "R-600a (isobutane) in a modern domestic fridge is:",
      ["A CFC", "A hydrocarbon A3 — flammable, still 608 if it is a small appliance", "Exempt from all recovery", "Type III"], 1,
      "HC fridges are still small appliances. Flammable. Recover with equipment listed for it."),
    Q("type1", "The 4 inches Hg Type I option is:",
      ["A dehydration micron target", "An alternate to the 80/90% recovery percentage", "Required on every window unit", "The Type III number"], 1,
      "Hit 90% (or 80%) OR 4\" Hg. Microns are a different pump after you braze."),
    Q("type1", "Self-contained recovery on a fridge with a dead compressor:",
      ["Cannot be used", "Is the right tool — you don't need the sealed compressor to run", "Requires 15\" Hg", "Voids Type I"], 1,
      "That's why self-contained exists. Dead compressor still gets 80% or 4\" Hg."),
    Q("type1", "Type I plus Core (no Type II) lets you open:",
      ["Any residential split", "Small appliances only", "Chillers", "Anything under 5 tons"], 1,
      "Window, fridge, PTAC. The split next door is Type II."),
  ];

  const TYPE2 = [
    Q("type2", "Type II certification covers:",
      ["Small appliances only", "High-pressure and very-high-pressure appliances except small appliances and MVAC", "Low-pressure chillers only", "Cars"], 1,
      "Splits, RTUs, racks, most HVAC. Not windows. Not R-123 centrifugals. Not cars."),
    Q("type2", "On the EPA 104°F cut, R-410A is:",
      ["Low-pressure", "Medium-pressure", "High-pressure", "Very-high-pressure"], 2,
      "R-410A is high-pressure. Very-high is R-13 / R-23 class. R-134a is medium."),
    Q("type2", "R-134a on that same cut is:",
      ["Low-pressure", "Medium-pressure", "High-pressure", "Type I always"], 1,
      "Medium-pressure. That's why large R-134a can require 15\" Hg, not 10\"."),
    Q("type2", "House 3-ton R-410A, recovery machine made after Nov 15, 1993. Required recovery level before opening:",
      ["10 inches Hg vacuum", "15 inches Hg vacuum", "0 inches Hg (0 psig)", "25 mm Hg absolute"], 2,
      "High-pressure, under 200 lb, post-1993 = 0\" vacuum = 0 psig. Not a micron pull."),
    Q("type2", "High-pressure appliance, 200 lb or more, recovery machine after Nov 15, 1993:",
      ["0 inches Hg", "4 inches Hg", "10 inches Hg", "15 inches Hg"], 2,
      "Post-1993 high-pressure ≥200 lb = 10\" Hg. 15\" is medium-pressure ≥200 lb. 4\" is the pre-1993 number."),
    Q("type2", "Medium-pressure appliance, 200 lb or more, modern recovery machine:",
      ["0 inches Hg", "10 inches Hg", "15 inches Hg", "25 mm Hg absolute"], 2,
      "15\" Hg. Trap: techs pick 15\" for 'the big 410A.' 410A is high-pressure — 10\" at ≥200 lb."),
    Q("type2", "0 inches of mercury vacuum on the 608 table means:",
      ["500 microns", "0 psig / atmospheric", "29.9 in Hg on a compound gauge", "Type III chiller pull"], 1,
      "0\" vacuum is atmospheric (0 psig). You did not dehydrate the system."),
    Q("type2", "Recovery equipment manufactured before Nov 15, 1993 on a high-pressure ≥200 lb system requires:",
      ["0 inches Hg", "4 inches Hg", "10 inches Hg", "15 inches Hg"], 1,
      "Pre-1993 high-pressure ≥200 lb = 4\". Today's truck is post-1993 = 10\"."),
    Q("type2", "Very-high-pressure appliances recover to:",
      ["15 inches Hg", "10 inches Hg", "0 inches Hg (0 psig) regardless of charge", "25 mm Hg abs"], 2,
      "Very-high never needs a deep 608 pull — 0 psig."),
    Q("type2", "Comfort-cooling leak-rate threshold (annual) is:",
      ["5%", "10%", "20%", "30%"], 1,
      "Comfort cooling 10%. Commercial refrigeration 20%. Industrial process 30%."),
    Q("type2", "A grocery rack (commercial refrigeration) leak-rate threshold is:",
      ["10%", "20%", "30%", "35%"], 1,
      "20%. 10% is comfort cooling. 30% is IPR. 35% is the old IPR number."),
    Q("type2", "Industrial process refrigeration leak-rate threshold is:",
      ["10%", "20%", "30%", "50%"], 2,
      "30% IPR. Don't pick 35% — that was pre-2019."),
    Q("type2", "Section 608 Subpart F leak-repair rules (ODS / substitutes) generally apply to appliances with a full charge of at least:",
      ["5 lb", "15 lb", "50 lb", "200 lb"], 2,
      "50 pounds under 40 CFR 82.157. AIM Part 84 uses 15 lb for many HFC appliances — know which rule the question is asking."),
    Q("type2", "Starting 2026, AIM Act HFC leak-repair (40 CFR 84) generally covers appliances with a full charge of at least:",
      ["5 lb", "15 lb", "50 lb only", "1,500 lb only"], 1,
      "15 lb of HFC (or listed high-GWP substitutes). 50 lb is the older Subpart F ODS trigger. 1,500 lb is related to some ALD rules."),
    Q("type2", "Once a covered appliance exceeds its leak-rate threshold, owners generally must repair within:",
      ["7 days", "30 days", "90 days always", "1 year"], 1,
      "30 days (with limited extensions, e.g. IPR shutdown). Retrofit/retire is the other door."),
    Q("type2", "A 100 lb comfort-cooling charge that needed 8 lb added 73 days after the last add: (8/100)×(365/73) ≈ 40%. That is:",
      ["Under all thresholds", "Over the 10% comfort-cooling threshold — repair duty is triggered", "Only a 609 issue", "Automatic loss of 608"], 1,
      "Annualized ~40% > 10%. Training math — use the official method and the logbook on the job."),
    Q("type2", "You may recover an isolated component (valved off) and treat the charge as:",
      ["The whole building", "That component's charge for the recovery target", "Always 200 lb", "Type I rules"], 1,
      "If you can isolate it, the inches apply to that piece."),
    Q("type2", "A non-major repair that will not open the appliance to atmosphere on medium/high/very-high pressure needs recovery to:",
      ["10 inches Hg always", "0 psig", "25 mm Hg abs", "500 microns"], 1,
      "Non-major, not opening to air: 0 psig is enough. Major = compressor, condenser, evaporator, aux heat exchanger."),
    Q("type2", "EPA's 'major repair' includes removing the:",
      ["Filter-drier only", "Compressor, condenser, evaporator, or auxiliary heat exchanger", "Thermostat", "Capacitor"], 1,
      "Those four. A drier swap that doesn't open the rest still needs recovery discipline, but the vacuum table treats major vs not."),
    Q("type2", "New R-22 equipment was banned:",
      ["January 1, 2010", "January 1, 2020", "January 1, 2025", "July 1, 1992"], 0,
      "New equipment 2010. Production/import of R-22 banned January 1, 2020. Only reclaimed/recovered supply."),
    Q("type2", "Under the AIM Act, new residential equipment using R-410A generally ended:",
      ["2010", "2020", "January 1, 2025", "Never"], 2,
      "2025 HFC restriction on new comfort equipment. Replacements are A2L (R-454B, R-32)."),
    Q("type2", "After you open a Type II system for repair you should:",
      ["Never change the drier", "Replace the liquid-line filter-drier", "Add mineral oil to 410A", "Skip evacuation if you hit 0 psig for 608"], 1,
      "New drier when you open it. 0 psig satisfies 608 recovery — you still pull microns to dry."),
    Q("type2", "If the appliance is leaking so badly you cannot hit the required inches:",
      ["Vent and start over", "Recover as far as you can and document why the target was impossible", "Ignore the table", "Switch to Type I 4\""], 1,
      "Good-faith recovery + a written reason. Not a shrug."),
    Q("type2", "Required 608 recovery inches are measured:",
      ["On the recovery machine while it is still running", "At the system after the machine is off and the reading settles", "Only with a micron gauge", "At the cylinder"], 1,
      "System service valves, machine off, needle settled. Not a moving suction."),
    Q("type2", "Nitrogen with a small HCFC-22 tracer for leak finding:",
      ["Is always illegal venting", "Is a listed exception when used as a trace — still not a free charge of 22", "Requires Type III", "Replaces recovery"], 1,
      "Trace gas exception exists. Don't hide a dump of R-22 behind the word 'trace.'"),
  ];

  const TYPE3 = [
    Q("type3", "Type III certification covers:",
      ["Window AC", "Residential 410A splits", "Low-pressure appliances such as centrifugal chillers", "MVAC"], 2,
      "R-11 / R-123 / R-1233zd class chillers. Splits are Type II."),
    Q("type3", "Required recovery level for low-pressure appliances with recovery gear made after Nov 15, 1993 is:",
      ["0 psig", "10 inches Hg", "15 inches Hg", "25 mm Hg absolute"], 3,
      "25 mm Hg absolute — about 29 inches of vacuum. Not 25 inches Hg. Units matter."),
    Q("type3", "25 mm Hg absolute is approximately:",
      ["0 psig", "10 inches Hg vacuum", "A deep vacuum (~29 inches Hg)", "500 microns exactly"], 2,
      "Absolute 25 mm Hg ≈ 29\" vacuum. Trap: 25 inches vs 25 millimeters."),
    Q("type3", "Recovery equipment manufactured before Nov 15, 1993 on low-pressure appliances requires:",
      ["0 psig", "4 inches Hg", "25 mm Hg absolute", "25 inches Hg"], 3,
      "Before November 15, 1993 the low-pressure level is 25 inches of mercury vacuum. On or after that date it is 25 mm Hg absolute. Do not swap the unit with the date."),
    Q("type3", "Low-pressure chillers often run the evaporator:",
      ["At 400 psig", "In a vacuum — air leaks IN, not out", "On R-410A", "Without a vessel"], 1,
      "Below atmospheric. Air and moisture leak in. That's why old machines have a purge."),
    Q("type3", "A purge unit on a low-pressure chiller:",
      ["Adds extra refrigerant", "Removes non-condensable air that leaked into the vessel", "Is a Type I tool", "Replaces recovery"], 1,
      "Air in, efficiency down, pressure up. Purge takes the air out (and a little refrigerant — recover that too)."),
    Q("type3", "The rupture disc on a low-pressure chiller is typically set around:",
      ["5 psig", "15 psig", "150 psig", "410 psig"], 1,
      "About 15 psig. Downstream of the disc should not be capped solid — know the piping."),
    Q("type3", "Leak-test a low-pressure chiller with:",
      ["Oxygen", "Shop air", "Dry nitrogen (and/or controlled warm water — never oxygen)", "A full refrigerant charge until it hisses"], 2,
      "Dry nitrogen. Some shops raise pressure with warm water on the waterside. Never oxygen."),
    Q("type3", "To raise a low-pressure vessel enough to leak-check, techs often:",
      ["Hit it with 300 psig nitrogen", "Use controlled heat / warm water so pressure rises a few psig", "Add oxygen", "Run the centrifugal dry"], 1,
      "A few psig above atmosphere is enough to find leaks. Don't treat it like a 410A condensing unit."),
    Q("type3", "R-123 is:",
      ["A high-pressure HFC used in splits", "An HCFC low-pressure chiller refrigerant (being replaced by HFOs such as R-1233zd)", "A hydrocarbon fridge gas", "R-410A rebranded"], 1,
      "Type III shop gas. Lower ODP than R-11, still an HCFC. HFO replacements are here."),
    Q("type3", "ASHRAE Standard 15 (machinery room) matters on Type III because:",
      ["It sets 608 vacuum inches", "Low-pressure refrigerants can asphyxiate; rooms need ventilation and alarms", "It bans nitrogen", "It is OSHA 30 only"], 1,
      "Equipment rooms, sensors, ventilation. 608 is recovery. 15 is not dying in a basement."),
    Q("type3", "Water tubes leak into a low-pressure chiller. First recovery concern is:",
      ["Ignore it", "Water in the refrigerant / oil — recover and handle as contaminated", "It becomes Type I", "Vent to dry it"], 1,
      "Tube leak = water in the charge. Don't dump it. Recover, separate, reclaim."),
    Q("type3", "Open-drive centrifugal compressors:",
      ["Never leak", "Have a shaft seal that can leak air in or refrigerant out", "Are Type I", "Don't need recovery"], 1,
      "Shaft seal is a Type III classic leak path."),
    Q("type3", "If leaks prevent reaching 25 mm Hg absolute you:",
      ["Vent the remainder", "Recover as low as you can without contaminating the gas — not above 0 psig — and document", "Stop at 15 inches Hg and leave", "Use oxygen to pressurize"], 1,
      "Lowest level you can reach without contaminating the recovered refrigerant. That pressure cannot sit above 0 psig. Do not vent the rest."),
    Q("type3", "Recovering liquid from a chiller first is often preferred because:",
      ["EPA forbids vapor recovery", "Liquid removal is faster; then you pull vapor to the required mm Hg", "It skips the vacuum", "It converts it to Type II"], 1,
      "Get the liquid out, then vapor to 25 mm Hg abs."),
    Q("type3", "A rupture disc that has blown:",
      ["Is a Type I piercing valve", "Has dumped charge — recover what's left, replace the disc, find why it lifted", "Should be capped forever", "Means 608 does not apply"], 1,
      "The charge went somewhere. Recover remainder, fix the cause (overpressure, plugged vent line)."),
    Q("type3", "High-efficiency purge units:",
      ["Increase refrigerant loss", "Reduce the refrigerant lost with the purged air", "Are illegal", "Replace 608 recovery"], 1,
      "Less refrigerant riding out with the air. Still recover what the purge collects."),
    Q("type3", "Pressurizing a low-pressure chiller with nitrogen for leak check:",
      ["Can exceed the rupture-disc setting if you are careless", "Has no limit", "Requires 410 psig", "Is always illegal"], 0,
      "Disc ~15 psig. Nitrogen behind a regulator, watch the gauge, don't lift the disc."),
    Q("type3", "Type III recovery target is measured in:",
      ["Psig gauge only", "Inches Hg vacuum like Type II", "mm Hg absolute", "Microns only"], 2,
      "Absolute millimeters of mercury. Type II is inches of vacuum. Don't mix the scales."),
    Q("type3", "R-11 is:",
      ["An HFC split-system gas", "A CFC low-pressure chiller refrigerant (legacy)", "A2L for houses", "CO2"], 1,
      "Old centrifugals. Highest ODP club. Still shows up on the paper and in plants."),
    Q("type3", "Before a major repair on a low-pressure appliance you must recover to the required mm Hg:",
      ["Only if the owner asks", "Yes — 608 applies to chillers the same as splits", "Only for CFC, not HFC", "Never — they run in a vacuum already"], 1,
      "Already in a vacuum is not 'already recovered.' Pull to the table."),
    Q("type3", "Adding refrigerant to a low-pressure chiller is often done through the:",
      ["Discharge only as liquid into the head", "Evaporator / charging valve with the unit in a vacuum so it pulls liquid in", "Rupture disc", "Purge exhaust"], 1,
      "The vessel in a vacuum will pull charge. Follow OEM. Don't slug the compressor."),
    Q("type3", "A dual-rupture-disc / relief arrangement exists so:",
      ["You can cap both", "You can isolate and replace a disc without leaving the vessel unprotected", "608 does not apply", "Nitrogen can be skipped"], 1,
      "Service the disc without an open hole to atmosphere the whole time."),
    Q("type3", "Universal certification includes Type III so a residential tech:",
      ["Must work chillers every week", "Is legal if a plant calls — most 608 cards for HVAC still sit Type II most days", "Can skip Core", "Can skip recovery on 410A"], 1,
      "Universal is the door card. Type II is still the daily HVAC work."),
    Q("type3", "The passing score on Type III is:",
      ["Different — 80%", "18 of 25 (72%), same as every proctored section", "12 of 25", "100%"], 1,
      "18/25 independently. A 24 on Core does not save a 17 on Type III."),
  ];

  function shuffle(arr) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) {
      const j = (Math.random() * (i + 1)) | 0;
      const t = a[i];
      a[i] = a[j];
      a[j] = t;
    }
    return a;
  }

  function shuffleChoices(item) {
    const order = item.choices.map(function (_, i) { return i; });
    const sh = shuffle(order);
    const choices = sh.map(function (i) { return item.choices[i]; });
    const a = sh.indexOf(item.a);
    return Object.assign({}, item, { choices: choices, a: a });
  }

  const BY = { core: CORE, type1: TYPE1, type2: TYPE2, type3: TYPE3 };

  function deck(kind) {
    const k = kind || "universal";
    if (k === "core") return shuffle(CORE).map(shuffleChoices);
    if (k === "type1") return shuffle(TYPE1).map(shuffleChoices);
    if (k === "type2") return shuffle(TYPE2).map(shuffleChoices);
    if (k === "type3") return shuffle(TYPE3).map(shuffleChoices);
    return shuffle(CORE).map(shuffleChoices)
      .concat(shuffle(TYPE1).map(shuffleChoices))
      .concat(shuffle(TYPE2).map(shuffleChoices))
      .concat(shuffle(TYPE3).map(shuffleChoices));
  }

  global.Epa608Exam = {
    CORE: CORE,
    TYPE1: TYPE1,
    TYPE2: TYPE2,
    TYPE3: TYPE3,
    ALL: CORE.concat(TYPE1, TYPE2, TYPE3),
    PASS: 18,
    EACH: 25,
    deck: deck,
    disclaimer:
      "2026 training paper: 25 questions a section, 18/25 (72%) to pass each. Covers current 608 / AIM topics. Not the official ESCO item bank. The real card is sat with an EPA-approved proctor.",
  };
})(typeof window !== "undefined" ? window : this);
